//Header
export const Access = {
    Admin: "ACCESS_ADMIN",
    User: "ACCESS_USER",
}

//Post permission
export const Post = {
    Comment: {
        POSTCOMMENT_PUBLIC_ALL_DELETE: "POSTCOMMENT_PUBLIC_ALL_DELETE",
        POSTCOMMENT_PUBLIC_ALL_LIKE: "POSTCOMMENT_PUBLIC_ALL_LIKE",
        POSTCOMMENT_PUBLIC_SELF_CREATE: "POSTCOMMENT_PUBLIC_SELF_CREATE",
        POSTCOMMENT_PUBLIC_SELF_DELETE: "POSTCOMMENT_PUBLIC_SELF_DELETE",
        POSTCOMMENTREPORT_PUBLIC_ALL_CREATE: "POSTCOMMENTREPORT_PUBLIC_ALL_CREATE"
    },
    POST_DELETED_ALL_DELETE: "POST_DELETED_ALL_DELETE",
    POST_DELETED_ALL_READ: "POST_DELETED_ALL_READ",
    POST_DELETED_ALL_UPDATE: "POST_DELETED_ALL_UPDATE",
    POST_DELETED_SELF_DELETE: "POST_DELETED_SELF_DELETE",
    POST_PENDING_ALL_APPROVE: "POST_PENDING_ALL_APPROVE",
    POST_PENDING_SELF_CREATE: "POST_PENDING_SELF_CREATE",
    POST_PUBLIC_ALL_DELETE: "POST_PUBLIC_ALL_DELETE",
    POST_PUBLIC_ALL_LIKE: "POST_PUBLIC_ALL_LIKE",
    POST_PUBLIC_ALL_READ: "POST_PUBLIC_ALL_READ",
    POST_PUBLIC_ALL_SAVE: "POST_PUBLIC_ALL_SAVE",
    POST_PUBLIC_ALL_UPDATE: "POST_PUBLIC_ALL_UPDATE",
    POST_PUBLIC_SELF_DELETE: "POST_PUBLIC_SELF_DELETE",
    POST_PUBLIC_SELF_UPDATE: "POST_PUBLIC_SELF_UPDATE",
    POST_READ: "POST_READ",
    POST_UNLISTED_ALL_DELETE: "POST_UNLISTED_ALL_DELETE",
    POST_UNLISTED_ALL_LIKE: "POST_UNLISTED_ALL_LIKE",
    POST_UNLISTED_ALL_READ: "POST_UNLISTED_ALL_READ",
    POST_UNLISTED_ALL_SAVE: "POST_UNLISTED_ALL_SAVE",
    POST_UNLISTED_ALL_UPDATE: "POST_UNLISTED_ALL_UPDATE",
    POST_UNLISTED_SELF_CREATE: "POST_UNLISTED_SELF_CREATE",
    POST_UNLISTED_SELF_DELETE: "POST_UNLISTED_SELF_DELETE",
    POST_UNLISTED_SELF_UPDATE: "POST_UNLISTED_SELF_UPDATE",
}

export const PostAction = {
    Read: "read",
    Save: "save",
    Like: "like",
    Update: "update",
    Delete: "delete",
    Report: "report",
    Comment: "comment",
    Highlight: "highlight",
    Unhighlight: "unhighlight",
    StickToTop: "sticktotop",
}

export const PostCommentAction = {
    Read: "read",
    Save: "save",
    Like: "like",
    Update: "update",
    Delete: "delete",
    Report: "report",
    Comment: "comment",
    Reply: "reply"
}

export const DocAction = {
    DOC_PUBLIC_ALL_READ: "DOC_PUBLIC_ALL_READ",
    DOC_DELETED_ALL_READ: "DOC_DELETED_ALL_READ",
    DOC_UNLISTED_ALL_READ: "DOC_UNLISTED_ALL_READ",
    DOC_PUBLIC_SELF_UPDATE: "DOC_PUBLIC_SELF_UPDATE",
    DOC_UNLISTED_SELF_UPDATE: "DOC_UNLISTED_SELF_UPDATE",
    DOC_PUBLIC_ALL_UPDATE: "DOC_PUBLIC_ALL_UPDATE",
    DOC_UNLISTED_ALL_UPDATE: "DOC_UNLISTED_ALL_UPDATE",
    DOC_DELETED_ALL_UPDATE: "DOC_DELETED_ALL_UPDATE",
    DOC_PUBLIC_SELF_DELETE: "DOC_PUBLIC_SELF_DELETE",
    DOC_UNLISTED_SELF_DELETE: "DOC_UNLISTED_SELF_DELETE",
    DOC_DELETED_SELF_DELETE: "DOC_DELETED_SELF_DELETE",
    DOC_PUBLIC_ALL_DELETE: "DOC_PUBLIC_ALL_DELETE",
    DOC_UNLISTED_ALL_DELETE: "DOC_UNLISTED_ALL_DELETE",
    DOC_DELETED_ALL_DELETE: "DOC_DELETED_ALL_DELETE",
    DOC_PENDING_SELF_CREATE: "DOC_PENDING_SELF_CREATE",
    DOC_PUBLIC_ALL_SAVE: "DOC_PUBLIC_ALL_SAVE",
    DOC_PUBLIC_ALL_LIKE: "DOC_PUBLIC_ALL_LIKE",
    DOC_PENDING_ALL_APPROVE: "DOC_PENDING_ALL_APPROVE",
    DOC_PENDING_SELF_UPLOAD: "DOC_PENDING_SELF_UPLOAD"
}