
//#region home 
export const GET_HIGHLIGHT_POSTS_REQUEST = "GET_HIGHLIGHT_POSTS_REQUEST";
export const GET_HIGHLIGHT_POSTS_SUCCESS = "GET_HIGHLIGHT_POSTS_SUCCESS";
export const GET_HIGHLIGHT_POSTS_FAILURE = "GET_HIGHLIGHT_POSTS_FAILURE";

export const HIGHLIGHT_A_POST_RESET = "HIGHLIGHT_A_POST_RESET";
export const HIGHLIGHT_A_POST_SUCCESS = "HIGHLIGHT_A_POST_SUCCESS";
export const HIGHLIGHT_A_POST_FAILURE = "HIGHLIGHT_A_POST_FAILURE";

export const DELETE_HIGHLIGHT_A_POST_RESET = "DELETE_HIGHLIGHT_A_POST_RESET";
export const DELETE_HIGHLIGHT_A_POST_SUCCESS = "DELETE_HIGHLIGHT_A_POST_SUCCESS";
export const DELETE_HIGHLIGHT_A_POST_FAILURE = "DELETE_HIGHLIGHT_A_POST_FAILURE";

export const GET_HIGHLIGHT_POSTS_IDS_REQUEST = "GET_HIGHLIGHT_POSTS_IDS_REQUEST";
export const GET_HIGHLIGHT_POSTS_IDS_SUCCESS = "GET_HIGHLIGHT_POSTS_IDS_SUCCESS";
export const GET_HIGHLIGHT_POSTS_IDS_FAILURE = "GET_HIGHLIGHT_POSTS_IDS_FAILURE";

export const STICK_A_POST_TO_TOP_REQUEST = "STICK_A_POST_TO_TOP_REQUEST";
export const STICK_A_POST_TO_TOP_SUCCESS = "STICK_A_POST_TO_TOP_SUCCESS";
export const STICK_A_POST_TO_TOP_FAILURE = "STICK_A_POST_TO_TOP_FAILURE";

export const GET_NEWEST_POSTS_REQUEST = "GET_NEWEST_POSTS_REQUEST";
export const GET_NEWEST_POSTS_SUCCESS = "GET_NEWEST_POSTS_SUCCESS";
export const GET_NEWEST_POSTS_FAILURE = "GET_NEWEST_POSTS_FAILURE";

export const GET_TRENDING_DOCUMENTS_LIST_REQUEST = "GET_TRENDING_DOCUMENTS_LIST_REQUEST";
export const GET_TRENDING_DOCUMENTS_LIST_SUCCESS = "GET_TRENDING_DOCUMENTS_LIST_SUCCESS";
export const GET_TRENDING_DOCUMENTS_LIST_FAILURE = "GET_TRENDING_DOCUMENTS_LIST_FAILURE";

export const GET_NEWEST_ACTIVITIES_LIST_REQUEST = "GET_NEWEST_ACTIVITIES_LIST_REQUEST";
export const GET_NEWEST_ACTIVITIES_LIST_SUCCESS = "GET_NEWEST_ACTIVITIES_LIST_SUCCESS";
export const GET_NEWEST_ACTIVITIES_LIST_FAILURE = "GET_NEWEST_ACTIVITIES_LIST_FAILURE";
//#endregion

//#region post 
export const LIKE_A_POST_REQUEST = "LIKE_A_POST_REQUEST";
export const LIKE_A_POST_SUCCESS = "UNLIKE_A_POST_SUCCESS";
export const LIKE_A_POST_FAILURE = "UNLIKE_A_POST_FAILURE";

export const UNLIKE_A_POST_REQUEST = "LIKE_A_POST_REQUEST";
export const UNLIKE_A_POST_SUCCESS = "LIKE_A_POST_SUCCESS";
export const UNLIKE_A_POST_FAILURE = "LIKE_A_POST_FAILURE";

export const SAVE_A_POST_SUCCESS = "SAVE_A_POST_SUCCESS";
export const SAVE_A_POST_FAILURE = "SAVE_A_POST_FAILURE";
export const SAVE_A_POST_RESET = "SAVE_A_POST_RESET";

export const UNSAVE_A_POST_RESET = "UNSAVE_A_POST_RESET";
export const UNSAVE_A_POST_SUCCESS = "UNSAVE_A_POST_SUCCESS";
export const UNSAVE_A_POST_FAILURE = "UNSAVE_A_POST_FAILURE";

export const DELETE_A_POST_RESET = "DELETE_A_POST_RESET";
export const DELETE_A_POST_SUCCESS = "DELETE_A_POST_SUCCESS";
export const DELETE_A_POST_FAILURE = "DELETE_A_POST_FAILURE";

export const EDIT_A_POST_RESET = "EDIT_A_POST_RESET";
export const EDIT_A_POST_SUCCESS = "EDIT_A_POST_SUCCESS";
export const EDIT_A_POST_FAILURE = "EDIT_A_POST_FAILURE";

export const APPROVE_A_POST_RESET = "APPROVE_A_POST_RESET";
export const APPROVE_A_POST_SUCCESS = "APPROVE_A_POST_SUCCESS";
export const APPROVE_A_POST_FAILURE = "APPROVE_A_POST_FAILURE";

export const REJECT_A_POST_RESET = "REJECT_A_POST_RESET";
export const REJECT_A_POST_SUCCESS = "REJECT_A_POST_SUCCESS";
export const REJECT_A_POST_FAILURE = "REJECT_A_POST_FAILURE";

export const REJECT_AND_FEEDBACK_A_POST_RESET = "REJECT_AND_FEEDBACK_A_POST_RESET";
export const REJECT_AND_FEEDBACK_A_POST_SUCCESS = "REJECT_AND_FEEDBACK_A_POST_SUCCESS";
export const REJECT_AND_FEEDBACK_A_POST_FAILURE = "REJECT_AND_FEEDBACK_A_POST_FAILURE";

export const REPORT_A_POST_RESET = "REPORT_A_POST_RESET";
export const REPORT_A_POST_SUCCESS = "REPORT_A_POST_SUCCESS";
export const REPORT_A_POST_FAILURE = "REPORT_A_POST_FAILURE";

export const GET_PENDING_POSTS_REQUEST = "GET_PENDING_POSTS_REQUEST";
export const GET_PENDING_POSTS_SUCCESS = "GET_PENDING_POSTS_SUCCESS";
export const GET_PENDING_POSTS_FAILURE = "GET_PENDING_POSTS_FAILURE";

export const GET_MY_POSTS_REQUEST = "GET_MY_POSTS_REQUEST";
export const GET_MY_POSTS_SUCCESS = "GET_MY_POSTS_SUCCESS";
export const GET_MY_POSTS_FAILURE = "GET_MY_POSTS_FAILURE";

export const GET_REPORTED_POSTS_REQUEST = "GET_REPORTED_POSTS_REQUEST";
export const GET_REPORTED_POSTS_SUCCESS = "GET_REPORTED_POSTS_SUCCESS";
export const GET_REPORTED_POSTS_FAILURE = "GET_REPORTED_POSTS_FAILURE";

export const RESOLVE_A_POST_RESET = "RESOLVE_A_POST_RESET";
export const RESOLVE_A_POST_SUCCESS = "RESOLVE_A_POST_SUCCESS";
export const RESOLVE_A_POST_FAILURE = "RESOLVE_A_POST_FAILURE";

export const CREATE_A_POST_RESET = "CREATE_A_POST_RESET";
export const CREATE_A_POST_SUCCESS = "CREATE_A_POST_SUCCESS";
export const CREATE_A_POST_FAILURE = "CREATE_A_POST_FAILURE";

export const GET_POST_BY_ID_REQUEST = "GET_POST_BY_ID_REQUEST";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const GET_POST_BY_ID_FAILURE = "GET_POST_BY_ID_FAILURE";
export const GET_POST_BY_ID_RESET = "GET_POST_BY_ID_RESET";

//relevant posts
export const GET_RELATIVE_SAME_CATEGORY_POSTS_RESET = "GET_RELATIVE_SAME_CATEGORY_POSTS_RESET";
export const GET_RELATIVE_SAME_CATEGORY_POSTS_SUCCESS = "GET_RELATIVE_SAME_CATEGORY_POSTS_SUCCESS";
export const GET_RELATIVE_SAME_CATEGORY_POSTS_FAILURE = "GET_RELATIVE_SAME_CATEGORY_POSTS_FAILURE";

export const GET_RELATIVE_SAME_AUTHOR_POSTS_RESET = "GET_RELATIVE_SAME_AUTHOR_POSTS_RESET";
export const GET_RELATIVE_SAME_AUTHOR_POSTS_SUCCESS = "GET_RELATIVE_SAME_AUTHOR_POSTS_SUCCESS";
export const GET_RELATIVE_SAME_AUTHOR_POSTS_FAILURE = "GET_RELATIVE_SAME_AUTHOR_POSTS_FAILURE";

//#endregion

//#region post category

export const GET_POST_CATEGORIES_REQUEST = "GET_POST_CATEGORIES_REQUEST";
export const GET_POST_CATEGORIES_HAVE_ALL_SUCCESS = "GET_POST_CATEGORIES_HAVE_ALL_SUCCESS";
export const GET_POST_CATEGORIES_SUCCESS = "GET_POST_CATEGORIES_SUCCESS";
export const GET_POST_CATEGORIES_FAILURE = "GET_POST_CATEGORIES_FAILURE";

//#endregion

//#region document
export const REACTION_A_DOCUMENT_REQUEST = "REACTION_A_DOCUMENT_REQUEST";
export const REACTION_A_DOCUMENT_SUCCESS = "REACTION_A_DOCUMENT_SUCCESS";
export const REACTION_A_DOCUMENT_FAILURE = "REACTION_A_DOCUMENT_FAILURE";

export const DELETE_A_DOCUMENT_RESET = "DELETE_A_DOCUMENT_RESET";
export const DELETE_A_DOCUMENT_SUCCESS = "DELETE_A_DOCUMENT_SUCCESS";
export const DELETE_A_DOCUMENT_FAILURE = "DELETE_A_DOCUMENT_FAILURE";

export const EDIT_A_DOCUMENT_RESET = "EDIT_A_DOCUMENT_RESET";
export const EDIT_A_DOCUMENT_SUCCESS = "EDIT_A_DOCUMENT_SUCCESS";
export const EDIT_A_DOCUMENT_FAILURE = "EDIT_A_DOCUMENT_FAILURE";

export const REJECT_A_DOCUMENT_RESET = "REJECT_A_DOCUMENT_RESET";
export const REJECT_A_DOCUMENT_SUCCESS = "REJECT_A_DOCUMENT_SUCCESS";
export const REJECT_A_DOCUMENT_FAILURE = "REJECT_A_DOCUMENT_FAILURE";

export const REJECT_AND_FEEDBACK_A_DOCUMENT_RESET = "REJECT_AND_FEEDBACK_A_DOCUMENT_RESET";
export const REJECT_AND_FEEDBACK_A_DOCUMENT_SUCCESS = "REJECT_AND_FEEDBACK_A_DOCUMENT_SUCCESS";
export const REJECT_AND_FEEDBACK_A_DOCUMENT_FAILURE = "REJECT_AND_FEEDBACK_A_DOCUMENT_FAILURE";

export const REPORT_A_DOCUMENT_RESET = "REPORT_A_DOCUMENT_RESET";
export const REPORT_A_DOCUMENT_SUCCESS = "REPORT_A_DOCUMENT_SUCCESS";
export const REPORT_A_DOCUMENT_FAILURE = "REPORT_A_DOCUMENT_FAILURE";

export const APPROVE_A_DOCUMENT_RESET = "APPROVE_A_DOCUMENT_RESET";
export const APPROVE_A_DOCUMENT_SUCCESS = "APPROVE_A_DOCUMENT_SUCCESS";
export const APPROVE_A_DOCUMENT_FAILURE = "APPROVE_A_DOCUMENT_FAILURE";

export const RESOLVE_A_DOCUMENT_RESET = "RESOLVE_A_DOCUMENT_RESET";
export const RESOLVE_A_DOCUMENT_SUCCESS = "RESOLVE_A_DOCUMENT_SUCCESS";
export const RESOLVE_A_DOCUMENT_FAILURE = "RESOLVE_A_DOCUMENT_FAILURE";

export const GET_DOCUMENTS_LIST_REQUEST = "GET_DOCUMENTS_LIST_REQUEST";
export const GET_DOCUMENTS_LIST_SUCCESS = "GET_DOCUMENTS_LIST_SUCCESS";
export const GET_DOCUMENTS_LIST_FAILURE = "GET_DOCUMENTS_LIST_FAILURE";

export const GET_MY_DOCUMENTS_REQUEST = "GET_MY_DOCUMENTS_REQUEST";
export const GET_MY_DOCUMENTS_SUCCESS = "GET_MY_DOCUMENTS_SUCCESS";
export const GET_MY_DOCUMENTS_FAILURE = "GET_MY_DOCUMENTS_FAILURE";

export const GET_PENDING_DOCUMENTS_REQUEST = "GET_PENDING_DOCUMENTS_REQUEST";
export const GET_PENDING_DOCUMENTS_SUCCESS = "GET_PENDING_DOCUMENTS_SUCCESS";
export const GET_PENDING_DOCUMENTS_FAILURE = "GET_PENDING_DOCUMENTS_FAILURE";

export const UPLOAD_DOCUMENT_REQUEST = "UPLOAD_DOCUMENT_REQUEST";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILURE = "UPLOAD_DOCUMENT_FAILURE";

export const GET_DOCUMENT_BY_ID_REQUEST = "GET_DOCUMENT_BY_ID_REQUEST";
export const GET_DOCUMENT_BY_ID_SUCCESS = "GET_DOCUMENT_BY_ID_SUCCESS";
export const GET_DOCUMENT_BY_ID_FAILURE = "GET_DOCUMENT_BY_ID_FAILURE";
export const GET_DOCUMENT_BY_ID_RESET = "GET_DOCUMENT_BY_ID_RESET";

export const GET_REPORTED_DOCUMENTS_REQUEST = "GET_REPORTED_DOCUMENTS_REQUEST";
export const GET_REPORTED_DOCUMENTS_SUCCESS = "GET_REPORTED_DOCUMENTS_SUCCESS";
export const GET_REPORTED_DOCUMENTS_FAILURE = "GET_REPORTED_DOCUMENTS_FAILURE";

//#endregion

//#region doc category & doc subject

export const GET_DOCUMENT_CATEGORIES_REQUEST = "GET_DOCUMENT_CATEGORIES_REQUEST";
export const GET_DOCUMENT_CATEGORIES_HAVE_ALL_SUCCESS = "GET_DOCUMENT_CATEGORIES_HAVE_ALL_SUCCESS";
export const GET_DOCUMENT_CATEGORIES_SUCCESS = "GET_DOCUMENT_CATEGORIES_SUCCESS";
export const GET_DOCUMENT_CATEGORIES_FAILURE = "GET_DOCUMENT_CATEGORIES_FAILURE";

export const GET_DOCUMENT_SUBJECTS_REQUEST = "GET_DOCUMENT_SUBJECTS_REQUEST";
export const GET_DOCUMENT_SUBJECTS_SUCCESS = "GET_DOCUMENT_SUBJECTS_SUCCESS";
export const GET_DOCUMENT_SUBJECTS_HAVE_ALL_SUCCESS = "GET_DOCUMENT_SUBJECTS_HAVE_ALL_SUCCESS";
export const GET_DOCUMENT_SUBJECTS_FAILURE = "GET_DOCUMENT_SUBJECTS_FAILURE";

//#endregion

//#region search

//search posts:
export const GET_POST_SEARCH_REQUEST = "GET_POST_SEARCH_REQUEST";
export const GET_POST_SEARCH_SUCCESS = "GET_POST_SEARCH_SUCCESS";
export const GET_POST_SEARCH_FAILURE = "GET_POST_SEARCH_FAILURE";

//saved posts:
export const GET_SAVED_POSTS_REQUEST = "GET_SAVED_POSTS_REQUEST";
export const GET_SAVED_POSTS_SUCCESS = "GET_SAVED_POSTS_SUCCESS";
export const GET_SAVED_POSTS_FAILURE = "GET_SAVED_POSTS_FAILURE";


//search document result:
export const GET_DOCUMENT_SEARCH_REQUEST = "GET_DOCUMENT_SEARCH_REQUEST";
export const GET_DOCUMENT_SEARCH_SUCCESS = "GET_DOCUMENT_SEARCH_SUCCESS";
export const GET_DOCUMENT_SEARCH_FAILURE = "GET_DOCUMENT_SEARCH_FAILURE";

//tag search result: (in header)
export const GET_TAG_SEARCH_REQUEST = "GET_TAG_SEARCH_REQUEST";
export const GET_TAG_SEARCH_SUCCESS = "GET_TAG_SEARCH_SUCCESS";
export const GET_TAG_SEARCH_FAILURE = "GET_TAG_SEARCH_FAILURE";

//search courses result:
export const GET_COURSE_SEARCH_REQUEST = "GET_COURSE_SEARCH_REQUEST";
export const GET_COURSE_SEARCH_SUCCESS = "GET_COURSE_SEARCH_SUCCESS";
export const GET_COURSE_SEARCH_FAILURE = "GET_COURSE_SEARCH_FAILURE";

//search quick search result (header)
export const GET_QUICK_SEARCH_REQUEST = "GET_QUICK_SEARCH_REQUEST";
export const GET_QUICK_SEARCH_SUCCESS = "GET_QUICK_SEARCH_SUCCESS";
export const GET_QUICK_SEARCH_FAILURE = "GET_QUICK_SEARCH_FAILURE";
export const GET_QUICK_SEARCH_RESET = "GET_QUICK_SEARCH_RESET";

//quick search tag for create post and document
export const GET_TAG_QUICK_QUERY_REQUEST = "GET_TAG_QUICK_QUERY_REQUEST";
export const GET_TAG_QUICK_QUERY_SUCCESS = "GET_TAG_QUICK_QUERY_SUCCESS";
export const GET_TAG_QUICK_QUERY_FAILURE = "GET_TAG_QUICK_QUERY_FAILURE";
export const GET_TAG_QUICK_QUERY_RESET = "GET_TAG_QUICK_QUERY_RESET";
//#endregion

//#region course list
export const GET_DAI_CUONG_COURSES_LIST_REQUEST = "GET_DAI_CUONG_COURSES_LIST_REQUEST";
export const GET_DAI_CUONG_COURSES_LIST_SUCCESS = "GET_DAI_CUONG_COURSES_LIST_SUCCESS";
export const GET_DAI_CUONG_COURSES_LIST_FAILURE = "GET_DAI_CUONG_COURSES_LIST_FAILURE";

export const GET_CS_NHOM_NGANH_COURSES_LIST_REQUEST = "GET_DAI_CUONG_COURSES_LIST_REQUEST";
export const GET_CS_NHOM_NGANH_COURSES_LIST_SUCCESS = "GET_DAI_CUONG_COURSES_LIST_SUCCESS";
export const GET_CS_NHOM_NGANH_COURSES_LIST_FAILURE = "GET_DAI_CUONG_COURSES_LIST_FAILURE";

export const GET_COURSES_LIST_REQUEST = "GET_DAI_CUONG_COURSES_LIST_REQUEST";
export const GET_COURSES_LIST_SUCCESS = "GET_DAI_CUONG_COURSES_LIST_SUCCESS";
export const GET_COURSES_LIST_FAILURE = "GET_DAI_CUONG_COURSES_LIST_FAILURE";

export const GET_MY_COURSES_REQUEST = "GET_MY_COURSES_REQUEST";
export const GET_MY_COURSES_SUCCESS = "GET_MY_COURSES_SUCCESS";
export const GET_MY_COURSES_FAILURE = "GET_MY_COURSES_FAILURE";

//#endregion

//#region course category
export const GET_COURSE_FALCUTY_CATEGORIES_REQUEST = "GET_COURSE_FALCUTY_CATEGORIES_REQUEST";
export const GET_COURSE_FALCUTY_CATEGORIES_SUCCESS = "GET_COURSE_FALCUTY_CATEGORIES_SUCCESS";
export const GET_COURSE_FALCUTY_CATEGORIES_FAILURE = "GET_COURSE_FALCUTY_CATEGORIES_FAILURE";

//#endregion

//#region modal
export const MODAL_CLOSE = "MODAL_CLOSE";
export const MODAL_OPEN = "MODAL_OPEN";

export const MODAL_BL_CLOSE = "MODAL_BL_CLOSE";
export const MODAL_BL_OPEN = "MODAL_BL_OPEN";

export const MODAL_BIG_CLOSE = "MODAL_BIG_CLOSE";
export const MODAL_BIG_OPEN = "MODAL_BIG_OPEN";
//#endregion

//#region tag
export const GET_TAG_BY_ID_REQUEST = "GET_TAG_BY_ID_REQUEST";
export const GET_TAG_BY_ID_SUCCESS = "GET_TAG_BY_ID_SUCCESS";
export const GET_TAG_BY_ID_FAILURE = "GET_TAG_BY_ID_FAILURE";

export const GET_RELATIVE_TAGS_REQUEST = "GET_RELATIVE_TAGS_REQUEST";
export const GET_RELATIVE_TAGS_SUCCESS = "GET_RELATIVE_TAGS_SUCCESS";
export const GET_RELATIVE_TAGS_FAILURE = "GET_RELATIVE_TAGS_FAILURE";
//#endregion

//#region authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";


//#endregion














export const GET_HEADINGS_LIST_REQUEST = "GET_HEADINGS_LIST_REQUEST";
export const GET_HEADINGS_LIST_SUCCESS = "GET_HEADINGS_LIST_SUCCESS";
export const GET_HEADINGS_LIST_FAILURE = "GET_HEADINGS_LIST_FAILURE";
export const SET_SEARCHING = "SET_SEARCHING";
